name: mapillary-road-surface-pipeline
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - aiohttp
      - duckdb
      - gdal
      - geopandas
      - mercantile
      - numpy
      - opencv-python
      - pandas
      - pyarrow
      - pygeodesy
      - pytest
      - pyyaml
      - requests
      - shapely
      - tqdm
      - vt2geojson